### ISSUE TITLE
Cannot reset kits on kits.lua

### ISSUE THREAD

**Issue by Thomspoon** [strykes/Oxide2Plugins#1]
I don't know if this is an error on my part or it's just not implemented, but is there a way to reset kits? I wiped my server and reset all the plugin info and it still says I have kits on cooldown.

**Comment by TheDoc777** [comment]
Hey, yes you can do /kit reset

**Comment by Thomspoon** [comment]
That isn't implemented into the lua version. Only the C# version.

**Comment by strykes** [comment]
lua plugins are here just because i wants to keep them, gives examples of lua plugins
but C# plugins are the latest plugins, and i only keep them updated

**Comment by Thomspoon** [comment]
Okay I see now. Thank you.
