### ISSUE TITLE
build.cs /build foundation.steps (TROLLING)

### ISSUE THREAD

**Issue by AndyMeusel** [strykes/Oxide2Plugins#5]
Is this fixable? 

Seems to build foundation steps just about anywhere you don't want them at any angle

**Comment by AndyMeusel** [comment]
Annoyingly the blueprint snaps the steps to exactly where i would like them

![image](https://cloud.githubusercontent.com/assets/2836205/25775799/9ff2e6de-32a5-11e7-9b9e-3769640d04af.png)

**Comment by v1ruspr0ne** [comment]
/buildhelp resources 0 /100 /200 do not work only items 284 to 411 which is highly frustrating when you accidentally crash your players by trying to guess the item id's

Thanks
